version: '3.9'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: exampledb
  simple_server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - "database"
    expose:
      - 8080